-- Run manually in the Supabase SQL Editor.
-- This seeds admin inventory only.
-- It does not change public merch.html.
-- It does not change checkout behavior.
--
-- Source of truth for this seed: the currently hard-coded public merch.html catalog.
-- Existing inventory counts are intentionally preserved on conflict.
-- Pins with "Price coming soon" are inserted hidden with price_cents = 0.

INSERT INTO public.shop_products (
    sku,
    name,
    description,
    category,
    price_cents,
    webador_url,
    image_url,
    quantity_total,
    quantity_sold,
    quantity_held,
    is_hidden,
    is_sold_out,
    sort_order
) VALUES
    (
        'CHARM-12MM',
        '12mm Stainless Steel Semicolon Charm',
        'A 12mm stainless steel semicolon charm for awareness, hope, and continuation.',
        'charm',
        500,
        NULL,
        'images/merch/charm-semicolon-product.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        10
    ),

    -- Awareness / hat pins. Public merch page lists prices as coming soon.
    (
        'HP2',
        'Awareness Gnome Hat Pin',
        'A whimsical gnome with a meaningful purpose.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp2-gnome-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        20
    ),
    (
        'HP3',
        'Semicolon Heart Hat Pin',
        'A simple yet powerful semicolon heart design.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp3-heart-semicolon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        21
    ),
    (
        'HP4',
        'Dual Awareness Ribbon Hat Pin',
        'A beautiful purple and teal awareness ribbon pin.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp4-purple-teal-awareness-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        22
    ),
    (
        'HP5',
        'Wings of Hope Hat Pin',
        'A tribute piece symbolizing remembrance, strength, and hope.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp5-winged-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        23
    ),
    (
        'HP6',
        'Rainbow of Hope Hat Pin',
        'A rainbow design celebrating hope after the storm.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp6-rainbow-awareness-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        24
    ),
    (
        'HP7',
        'Fighting Together Hat Pin',
        'A symbol of courage, resilience, and community support.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp7-fighting-together-hat-pin-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        25
    ),
    (
        'HP8',
        'Blooming Hope Hat Pin',
        'A bright flower design rooted in healing and growth.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp8-flower-awareness-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        26
    ),
    (
        'HP9',
        'Dove of Peace Hat Pin',
        'A graceful dove symbolizing peace, comfort, remembrance, and hope.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp9-dove-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        27
    ),
    (
        'HP10',
        'Awareness Butterfly Hat Pin',
        'A butterfly and ribbon design representing healing and new beginnings.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp10-butterfly-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        28
    ),
    (
        'HP11',
        'Love, Hope & Awareness Hat Pin',
        'A powerful combination of peace, love, and hope.',
        'accessory',
        0,
        NULL,
        'images/merch/clean/hp11-peace-heart-ribbon-charm-clean.png',
        0,
        0,
        0,
        TRUE,
        FALSE,
        29
    ),

    -- Crystal mushrooms. Public merch page lists these as $3 each / 2 for $5.
    (
        'MY2',
        'Yellow Aventurine Mushroom Set',
        'Warm golden-yellow polished stone mushrooms with natural dark inclusions.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/my2-yellow-aventurine-mushrooms-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        40
    ),
    (
        'MGRU',
        'Green Stone Mushroom',
        'A polished green stone mushroom with natural marbling and earthy character.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/mgru-green-stone-mushroom-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        41
    ),
    (
        'MU2',
        'Unakite Mushroom Set',
        'Earthy green polished stone mushrooms with natural variation.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/mu2-unakite-mushrooms-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        42
    ),
    (
        'MP',
        'Purple Stone Mushroom',
        'A polished purple stone mushroom with a bright, glossy finish.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/mp-purple-stone-mushroom-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        43
    ),
    (
        'MBL',
        'Lapis Lazuli Mushroom Set',
        'Deep blue polished stone mushrooms with natural golden flecks.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/mbl-lapis-lazuli-mushrooms-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        44
    ),
    (
        'MOP',
        'Opalite Mushroom Set',
        'Soft opalescent mushroom pieces with gentle blue and golden glow.',
        'accessory',
        300,
        NULL,
        'images/merch/clean/mop-opalite-mushrooms-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        45
    ),

    -- Existing crystal hearts included as safe upserts so this file can seed the full catalog.
    (
        'HOC',
        'Orange Howlite Heart',
        'Polished orange howlite crystal heart with natural white marbling.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/hoc-orange-howlite-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        60
    ),
    (
        'HOWC',
        'Orange Imperial Jasper Heart',
        'Polished orange imperial jasper heart with soft banding and earthy tones.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/howc-orange-imperial-jasper-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        61
    ),
    (
        'HO',
        'Orange Aventurine Heart',
        'Polished orange aventurine crystal heart with a bright, hopeful finish.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/ho-orange-aventurine-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        62
    ),
    (
        'HPBC',
        'Pink Brecciated Jasper Heart',
        'Polished pink brecciated jasper heart with bold natural patterning.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/hpbc-pink-brecciated-jasper-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        63
    ),
    (
        'HPC',
        'Pink Howlite Heart',
        'Polished pink howlite heart with soft marbling and a gentle finish.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/hpc-pink-howlite-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        64
    ),
    (
        'HPC2',
        'Pink Composite Jasper Heart',
        'Polished pink composite jasper heart with colorful natural-style variation.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/hpc2-pink-composite-jasper-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        65
    ),
    (
        'HA',
        'Rainbow Mosaic Heart',
        'Polished rainbow mosaic heart with bright mixed colors and an uplifting finish.',
        'awareness',
        300,
        NULL,
        'images/merch/clean/ha-rainbow-mosaic-heart-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        66
    ),

    -- Handmade / other public merch items.
    (
        'JB7',
        'Twizted Journeys Keepsake Jewelry Box Gift Set',
        'Hand-painted keepsake jewelry box gift set with awareness accessories, semicolon artwork, dragonflies, and messages of hope, strength, and continuation.',
        'other',
        3299,
        NULL,
        'images/merch/clean/jb7-keepsake-box-complete-set.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        80
    ),
    (
        'BEAR',
        'Grateful Bear Shelf Sitter',
        'A quirky, one-of-a-kind handmade shelf sitter with two grateful bear companions and a colorful heart centerpiece.',
        'other',
        1999,
        NULL,
        'images/merch/clean/grateful-bear-shelf-sitter-showcase.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        81
    ),
    (
        'UT4',
        'Miniature Unicorn Figurines',
        'Hand-painted miniature unicorns with glitter accents, teal or purple details, and semicolon markings.',
        'other',
        999,
        NULL,
        'images/merch/clean/ut4-ut7-mini-unicorn-figurines-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        82
    ),
    (
        'VDD2',
        'Patchwork Companion Figurine',
        'A glittery, hand-painted patchwork companion with oversized eyes, stitched details, and a wonderfully quirky personality.',
        'other',
        1799,
        NULL,
        'images/merch/clean/vdd2-vdd5-patchwork-companion-front-back-clean.png',
        0,
        0,
        0,
        FALSE,
        FALSE,
        83
    ),
    (
        'U1',
        'Twizted Semicolon Unicorn Candle Holder',
        'Hand-painted unicorn candle holder with teal and purple accents, semicolon details, and a glittering candle cup.',
        'other',
        2999,
        NULL,
        NULL,
        0,
        0,
        0,
        FALSE,
        FALSE,
        84
    ),
    (
        'U22P',
        'Momma and Foal Figurine',
        'Hand-painted momma and foal fantasy figurine in Twizted-inspired colors.',
        'other',
        2499,
        NULL,
        NULL,
        0,
        0,
        0,
        FALSE,
        FALSE,
        85
    ),
    (
        'GP5',
        'Gothic Fairy Statue',
        'A mystical fairy statue resting among dark blossoms and emerald leaves, finished in metallic greens and silvers.',
        'other',
        2999,
        NULL,
        NULL,
        0,
        0,
        0,
        FALSE,
        FALSE,
        86
    )
ON CONFLICT (sku) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    price_cents = EXCLUDED.price_cents,
    image_url = EXCLUDED.image_url,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();
